project:
  type: book
  output-dir: _output

book:
  title: "Financial Mathematics - Class 1"
  subtitle: "A Student-Friendly Guide"
  author: "MBA Program"
  date: today
  chapters:
    - index.qmd
    - basic_notions.qmd
    - bonds.qmd
    - value_function.qmd
    - interest_rates.qmd
    - cheat_sheet.qmd
    - exercises.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    html-math-method: mathjax
  pdf:
    documentclass: scrbook
    toc: true
    toc-depth: 3
    number-sections: true
    geometry:
      - margin=1in
    include-in-header:
      text: |
        \usepackage{amsmath}
        \usepackage{tikz}
        \usetikzlibrary{arrows,positioning,calc,shapes}
        \usepackage{longtable}
        \usepackage{booktabs}
        \usepackage{array}
        \usepackage{float}
        \usepackage{needspace}
        % Keep tables together on one page
        \usepackage{placeins}
        % Better spacing for figures
        \setlength{\intextsep}{12pt plus 2pt minus 2pt}
        \setlength{\textfloatsep}{12pt plus 2pt minus 2pt}
        % Prevent tables from breaking across pages
        \AtBeginEnvironment{longtable}{\needspace{10\baselineskip}}

execute:
  enabled: false
